basic_settings:
  site_title: jaklilia
  favicon_image: /images/favicon.ico

header_settings:
  logo_image: /images/logo.svg
  logo_width: 100

menu_settings:
  menu_items:
    - title: 'Witamy!'
      url: '/'
    - title: 'Aktualności'
      url: '/aktualnosci'      
    - title: 'Nasza misja'
      url: '/misja'
    - title: 'Oferta'
      url: '/oferta'
    - title: 'Opinie'
      url: '/opinie'      
#    - title: 'Blog'
#      url: '/blog/'
    - title: 'O nas'
      url: '/o-nas/'      
    - title: 'Kontakt'
      url: '/kontakt'

footer_settings:
  footer_tagline: Witaj w miejscu, w którym znajdziesz przestrzeń na rozwijanie swojego wewnętrznego piękna!

hero_settings:
  overlay_opacity: 0

post_settings:
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/f/mrgjlozj'
  confirmation_url: '/thanks'
  email_subject: 'jaklilia - formularz kontaktowy'
  send_button_text: 'Wyślij wiadomość'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#2A2F36'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  accent_color: '#e19bb7'
  border_color: '#dddddd'
  hero_background_color: '#132930'
  hero_gradient_color: '#e19bb7'	
  hero_text_color: '#ffffff'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Muli:300,400,600,700" rel="stylesheet"><link href="https://fonts.googleapis.com/css2?family=Cookie&display=swap&text=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789%C4%85%C4%84%C4%99%C4%98%C4%87%C4%86%C5%9B%C5%9A%C5%BA%C5%B9%C5%BC%C5%BB%C3%B3%C5%84%C5%83%C5%82%C5%81!?" rel="stylesheet">'
  title_font: '"Cookie", sans-serif'
  menu_font: '"Cookie", sans-serif'
  body_font: '"Multi", sans-serif'
  regular_weight: 300
  bold_weight: 400
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: 0
  menu:
    small_size: 50
    medium_size: 30
    large_size: 30
    weight: 300
    letter_spacing: 0
  h1:
    small_size: 35
    medium_size: 45
    large_size: 60
    weight: 400
    letter_spacing: 0
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 300
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 300
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 12
    medium_size: 14
    large_size: 18
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 15
    medium_size: 25
    large_size: 35
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

avatar_settings:
    small_size: 300
    medium_size: 460
    large_size: 600

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""